### ISSUE TITLE
Memory problems

### ISSUE THREAD

**Issue by ted42** [rfjakob/cshatag#1]
I noticed the return values from malloc are not checked in case the system runs out of memory (which really can happen).
And the allocated memory isn't freed. Now this is not a big problem, since the program can only process one file at a time. But it is not clean.
Also, when the argument is a file which already has a checksum, valgrind notices an "Conditional jump or move depends on uninitialised value".

If this project isn't actively maintained I could fix those problems provided i find the time to do that.

**Comment by rfjakob** [comment]
Thanks for the report! I will look at the issues

**Comment by ted42** [comment]
#2 takes care of these issues
