### ISSUE TITLE
Storing attributes to special file that's immutable, with a timestamp

### ISSUE THREAD

**Issue by digisepio** [rfjakob/cshatag#16]
Hello.

Thanks for your work, works great. 

We run Linux LX zones in Illumnos VMs (OmniOS), and the base filesystem there is ZFS. ZFS On Linux (ZOL) already has fix for use of xattrs, but this fails on the LX VMs because xattr are not accessible in the VM because of the way ZFS stores file attributes. I'd like to propose a work-around - kindly allow storage of the attributes to a hidden/immutable file in the same directory as the file as an option.

The attached screenshot is from the OmniOS gitter discussion group.

Thanks.

<img width="938" alt="Screenshot 2021-04-12 at 23 31 23" src="https://user-images.githubusercontent.com/73491481/114440250-88372c80-9be7-11eb-8864-a38e59b757f5.png">

**Comment by digisepio** [comment]
![Uploading Screenshot 2021-04-12 at 23.31.23.png…]()

**Comment by rfjakob** [comment]
Sorry, xattrs are like "the core feature" of cshatag. Maybe you can use https://github.com/Tripwire/tripwire-open-source which stores the checksums in a database?
