### ISSUE TITLE
thanks for this

### ISSUE THREAD

**Issue by G2G2G2G** [rfjakob/cshatag#18]
Couldn't get shatag working after like an hour trying with extended attributes etc with make-no-sense verbose things like `<missing>`

Anyway this worked out of the box and I can see them via getfattr 

How do I compile for ARM using the makefile? I ran this and it worked fine (and I am using it already, just wondering about the makefile):
`env GOOS=linux GOARCH=arm GOARM=7 go build .`

but I read the makefile and no idea what's going on in there..

also another question:
https://ostechnix.com/how-to-edit-a-file-without-changing-its-timestamps-in-linux/
doing this makes it think a file is corrupt, there are other things that sometimes change files but not mtime, are there any methods of avoiding this or not really?

**Comment by rfjakob** [comment]
Hi!

Running

    make clean
    GOOS=linux GOARCH=arm GOARM=7 make

should be enough:

```
$ make clean
rm -f cshatag README.md

$ GOOS=linux GOARCH=arm GOARM=7 make
CGO_ENABLED=0 go build "-ldflags=-X main.GitVersion=v2.0-4-g8ce1861-dirty"
cat header.md > README.md
MANWIDTH=80 man ./cshatag.1 >> README.md

$ file cshatag
cshatag: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, Go BuildID=tc63qVkd86T8tioZAI8k/swkCTPggGvZ1aa4kgso5/NmwdhLdwl2Qil6QWI_CQ/jBjFxu5JdAXC9_bhEId5, not stripped
```

But running "go build" directly is also fine, only thing is that then cshatag does not know its version (it will print "(version unknown)" in the help text).

2nd question: Yes this will show up as a corrupt file. Unfortunately, there is no way to distinguish an edit like this from a real corruption.
