### ISSUE TITLE
Feature request: add --untag flag

### ISSUE THREAD

**Issue by bjornfor** [rfjakob/cshatag#5]
Currently one have to read the man page to know how to undo / untag files previously tagged with cshatag. (And the command example given feels like it leaks cshatag implementation detail.) Perhaps adding a --untag flag (or --undo?) would help?

At the same time, we might want to add --help flag too, to more easily find the new flag.

**Comment by rfjakob** [comment]
Fixed via https://github.com/rfjakob/cshatag/pull/14

**Comment by bjornfor** [comment]
Thanks!
