### ISSUE TITLE
Test file is always corrupt

### ISSUE THREAD

**Issue by fturco** [rfjakob/cshatag#7]
`cshatag` always report corruption when I create an empty `foo` file for test purposes:

```
$ touch foo
fturco@desktop ~ 21:27:22 0 $ cshatag foo
<outdated> foo
 stored: 0000000000000000000000000000000000000000000000000000000000000000 0000000000.000000000
 actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 1550262442.004366404
fturco@desktop ~ 21:27:25 0 $ cshatag foo
Error: corrupt file "foo"
<corrupt> foo
 stored: 0000000000000000000000000000000000000000000000000000000000000000 1550262442.004366404
 actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 1550262442.004366404
```

Some more details:

```
$ getfattr foo 
# file: foo
user.shatag.sha256
user.shatag.ts
```

I'm using the latest cshatag version for this git repository on a Gentoo Linux system.

**Comment by rfjakob** [comment]
I can confirm this bug. Looks like I broke it in 3a882996076f104ba8c8bd210f4160495813dc6e two months ago, darn.

**Comment by rfjakob** [comment]
I have fixed the bug, and I have also added automated tests via Travis to catch something like this earlier. I have added the Travis "build passing" link to the front page at https://github.com/rfjakob/cshatag .

Thanks for the report!
